/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MK02FN128xxx10
package_id: MK02FN128VFM10
mcu_data: ksdk2_0
processor_version: 25.06.10
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 6b12f652-b565-4083-9908-ad7f7499c86c
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA'
- type: 'edma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'edma_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableMinorLoopMapping: 'false'
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - ERCA: 'fixedPriority'
      - enableDebugMode: 'true'
    - dma_table:
      - 0: []
    - edma_channels:
      - 0:
        - apiMode: 'nontransTCD'
        - edma_channel:
          - channel_prefix_id: 'CH0'
          - uid: '1758780798996'
          - eDMAn: '0'
          - eDMA_source: 'kDmaRequestMux0UART0Rx'
          - enableTriggerPIT: 'false'
          - init_channel_priority: 'false'
          - edma_channel_Preemption:
            - enableChannelPreemption: 'false'
            - enablePreemptAbility: 'false'
            - channelPriority: '0'
        - resetChannel: 'true'
        - enableChannelRequest: 'true'
        - enableAsyncRequest: 'false'
        - tcd_configuration:
          - 0:
            - uid: '1758780799003'
            - tcdID: 'CH0_TCD0'
            - ssize: 'kEDMA_TransferSize1Bytes'
            - saddr_expr: '&UART0->D'
            - saddr_def: ''
            - soff: '0'
            - soff_def: ''
            - smod: 'kEDMA_ModuloDisable'
            - dsize: 'kEDMA_TransferSize1Bytes'
            - daddr_expr: '&rxRing[0]'
            - daddr_def: '#include "uart/uart.h"'
            - doff: '1'
            - doff_def: ''
            - dmod: 'kEDMA_Modulo1Kbytes'
            - nbytes: '1'
            - MLconfig:
              - offsetType: 'disabled'
              - mloff: '0'
            - enableChannelLinkMinor: 'false'
            - linkedChannelMinor: '1758780798996'
            - bandwidthControl: 'disabled'
            - citer: '1024'
            - slast: '0'
            - enableChannelLinkMajor: 'false'
            - linkedChannelMajor: '1758780798996'
            - disableERQ: 'false'
            - enableScatterGather: 'true'
            - sga: '1758780799003'
            - interruptSources: ''
        - constantTCD: 'false'
        - no_init_uid: '1758780799002'
        - initializedTCD: '1758780799003'
        - channel_enabled_interrupts: ''
        - init_interruptsEnable: 'false'
        - interrupt_channel:
          - IRQn: 'DMA0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - errInterruptConfig:
      - enableErrInterrupt: 'false'
      - errorInterrupt:
        - IRQn: 'DMA_Error_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t DMA_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = true
};
AT_NONCACHEABLE_SECTION_ALIGN_INIT(edma_tcd_t DMA_CH0_TCDs_config[1], 0x20U)
 = {
  {
    .SADDR = (uint32_t) &UART0->D,
    .SOFF = (uint16_t) 0,
    .ATTR = DMA_ATTR_SMOD(kEDMA_ModuloDisable) | DMA_ATTR_SSIZE(kEDMA_TransferSize1Bytes) | DMA_ATTR_DMOD(kEDMA_Modulo1Kbytes) | DMA_ATTR_DSIZE(kEDMA_TransferSize1Bytes),
    .NBYTES = DMA_NBYTES_MLOFFYES_NBYTES(1U) | DMA_NBYTES_MLOFFYES_SMLOE(0U) | DMA_NBYTES_MLOFFYES_DMLOE(0U) | DMA_NBYTES_MLOFFYES_MLOFF(0),
    .SLAST = DMA_SLAST_SLAST(0),
    .DADDR = (uint32_t) &rxRing[0],
    .DOFF = (uint16_t) 1,
    .CITER = DMA_CITER_ELINKNO_ELINK(0U) | DMA_CITER_ELINKNO_CITER(1024U),
    .DLAST_SGA = (uint32_t)(&DMA_CH0_TCD0_config),
    .CSR = DMA_CSR_START(0U) | DMA_CSR_INTMAJOR(0U) | DMA_CSR_INTHALF(0U) | DMA_CSR_DREQ(0U) | DMA_CSR_ESG(1U) | DMA_CSR_MAJORELINK(0U) | DMA_CSR_MAJORLINKCH(0) | DMA_CSR_BWC(0U),
    .BITER = DMA_BITER_ELINKNO_ELINK(0U) | DMA_BITER_ELINKNO_BITER(1024U)
  }
};

static void DMA_init(void) {
  /* DMA minor loop mapping */
  EDMA_EnableMinorLoopMapping(DMA_DMA_BASEADDR, false);

  /* Channel CH0 initialization */
  /* Set the source kDmaRequestMux0UART0Rx request in the DMAMUX */
  DMAMUX_SetSource(DMA_DMAMUX_BASEADDR, DMA_CH0_DMA_CHANNEL, DMA_CH0_DMA_REQUEST);
  /* Enable the channel 0 in the DMAMUX */
  DMAMUX_EnableChannel(DMA_DMAMUX_BASEADDR, DMA_CH0_DMA_CHANNEL);
  /* DMA channel 0 reset */
  EDMA_ResetChannel(DMA_DMA_BASEADDR, DMA_CH0_DMA_CHANNEL);
  /* DMA TCD CH0_TCD0 initialization */
  EDMA_InstallTCD(DMA_DMA_BASEADDR, DMA_CH0_DMA_CHANNEL, (edma_tcd_t *)&DMA_CH0_TCD0_config);
  /* DMA channel 0 peripheral request */
  EDMA_EnableChannelRequest(DMA_DMA_BASEADDR, DMA_CH0_DMA_CHANNEL);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMAMUX_Init(DMA_DMAMUX_BASEADDR);
  EDMA_Init(DMA_DMA_BASEADDR, &DMA_config);

  /* Initialize components */
  DMA_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
